/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.brasilsoldado.view;

import com.brasilsoldado.controller.PersonController;
import com.brasilsoldado.model.Person;
import com.brasilsoldado.helpers.Formatacao;
import com.brasilsoldado.view.person.ViewPersonUpdate;

/**
 *
 * @author joaopedro
 */
public class ViewDashboard extends javax.swing.JFrame {

    final PersonController personController = new PersonController();
    Person person;

    public ViewDashboard() {
        initComponents();
    }

    /**
     * Creates new form ViewDashboard
     *
     * @param email
     */
    public ViewDashboard(String email) {
        person = this.personController.show(email);
        initComponents();
        this.welcome.setText("Bem Vindo, " + person.getName() + "!");
        this.name.setText("Nome: " + person.getName());
        this.surname.setText("Sobrenome: " + person.getSurname());
        this.birthday.setText("Data de Nascimento: " + Formatacao.ajustaDataDMA(person.getBirthday() + ""));
        this.cpf.setText("CPF: " + person.getCpf());
        this.mothersName.setText("Nome da Mãe: " + person.getMomsName());
        this.fathersName.setText("Nome do Pai: " + person.getDadsName());
        switch (person.getType()) {
            case 1:
                this.type.setText("Situação: Alistado");
                break;
            case 777:
                this.type.setText("Situação: Capitão");
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        surname = new javax.swing.JLabel();
        cpf = new javax.swing.JLabel();
        birthday = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        mothersName = new javax.swing.JLabel();
        fathersName = new javax.swing.JLabel();
        update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(57, 128, 65));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        welcome.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        welcome.setForeground(new java.awt.Color(254, 254, 254));
        welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome.setText("Bem Vindo João Pedro!");

        name.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(254, 254, 254));
        name.setText("- Nome: João Pedro");

        surname.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        surname.setForeground(new java.awt.Color(254, 254, 254));
        surname.setText("- Sobrenome: Basso Audibert");

        cpf.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cpf.setForeground(new java.awt.Color(254, 254, 254));
        cpf.setText("- CPF: 026.890.330-11");

        birthday.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        birthday.setForeground(new java.awt.Color(254, 254, 254));
        birthday.setText("- Data de Nascimento: 16/05/2001");

        type.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        type.setForeground(new java.awt.Color(254, 254, 254));
        type.setText("- SItuação: Alistado");

        mothersName.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        mothersName.setForeground(new java.awt.Color(254, 254, 254));
        mothersName.setText("- Nome da Mãe: Adriana Basso Audibert");

        fathersName.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        fathersName.setForeground(new java.awt.Color(254, 254, 254));
        fathersName.setText("- Nome do Pai: Edson Audibert");

        update.setText("Editar Informações");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(name)
                        .addGap(246, 246, 246)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(surname)
                    .addComponent(birthday)
                    .addComponent(cpf)
                    .addComponent(type)
                    .addComponent(mothersName)
                    .addComponent(fathersName))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(surname)
                .addGap(41, 41, 41)
                .addComponent(birthday)
                .addGap(41, 41, 41)
                .addComponent(cpf)
                .addGap(41, 41, 41)
                .addComponent(type)
                .addGap(41, 41, 41)
                .addComponent(mothersName)
                .addGap(41, 41, 41)
                .addComponent(fathersName)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        new ViewPersonUpdate("joaopedro.audibert@gmail.com").setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthday;
    private javax.swing.JLabel cpf;
    private javax.swing.JLabel fathersName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mothersName;
    private javax.swing.JLabel name;
    private javax.swing.JLabel surname;
    private javax.swing.JLabel type;
    private javax.swing.JButton update;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
